name: clone repos

on: [push]

jobs:
  cloning:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          repository: venkat785/test-1
          path: test-1
