name: fetch_other_repo
on: push

jobs:
  build:
    name: clone repo
    runs-on: ubuntu-latest
    steps:
      - name: clone test-3
        run: |
          echo "testing failure"
          sleep 10s
      - uses: convictional/trigger-workflow-and-wait@v1.3.0
        with:
          owner: venkat785
          repo: test-1
          github_token: ${{ secrets.SECRETS_TOKEN }}
          workflow_file_name: deploy.yml
          wait_interval: 10
      - uses: convictional/trigger-workflow-and-wait@v1.3.0
        with:
          owner: venkat785
          repo: test-2
          github_token: ${{ secrets.SECRETS_TOKEN }}
          workflow_file_name: deploy.yml
          wait_interval: 10
      - uses: convictional/trigger-workflow-and-wait@v1.3.0
        with:
          owner: venkat785
          repo: test-3
          github_token: ${{ secrets.SECRETS_TOKEN }}
          workflow_file_name: deploy.yml
          wait_interval: 10
      - uses: convictional/trigger-workflow-and-wait@v1.3.0
        with:
          owner: venkat785
          repo: test-4
          github_token: ${{ secrets.SECRETS_TOKEN }}
          workflow_file_name: deploy.yml
          wait_interval: 10
      - uses: convictional/trigger-workflow-and-wait@v1.3.0
        with:
          owner: venkat785
          repo: test-5
          github_token: ${{ secrets.SECRETS_TOKEN }}
          workflow_file_name: deploy.yml
          wait_interval: 10
      - uses: convictional/trigger-workflow-and-wait@v1.3.0
        with:
          owner: venkat785
          repo: test-6
          github_token: ${{ secrets.SECRETS_TOKEN }}
          workflow_file_name: deploy.yml
          wait_interval: 10
      - uses: convictional/trigger-workflow-and-wait@v1.3.0
        with:
          owner: venkat785
          repo: test-7
          github_token: ${{ secrets.SECRETS_TOKEN }}
          workflow_file_name: deploy.yml
          wait_interval: 10
      - name: test results
        run: |
          echo "test success "
          sleep 10s
