name: fetch_other_repo
on: push

jobs:
  build:
    name: clone repo
    runs-on: ubuntu-latest
    steps:
      - name: clone test-1
        run: |
          echo "test-1"
          sleep 10s
      - uses: convictional/trigger-workflow-and-wait@v1.3.0
        with:
          owner: venkat785
          repo: test-1
          github_token: ${{ secrets.SECRETS_TOKEN }}
          workflow_file_name: deploy.yml
      - name: test results
        run: |
          echo "test-1 success"
          sleep 10s
